# Generated by Django 5.1.4 on 2025-01-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(default="pending", max_length=50),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Наличные"),
                    ("TRANSFER", "Перевод на счет"),
                    ("stripe", "Stripe"),
                ],
                max_length=50,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
